apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-result-vote
spec:
  rules:
    - host: localhost
      http:
        paths:
        - backend:
            serviceName: vote-service
            servicePort: 80
      http:
        paths:
        - backend:
            serviceName: result-service
            servicePort: 80