apiVersion: v1
kind: Service
metadata:
  labels:
    name: vote
  name: vote
spec:
  type: ClusterIP
  ports:
  - name: "vote-service"
    port: 3000
    targetPort: 3000
  selector:
    name: vote
  
