apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include vote.fullname" . }}
  labels:
    app: {{ include vote.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include vote.name" . }}
  template:
    metadata:
      labels:
        app: {{ include vote.name" . }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 80
          name: vote
