apiVersion: v1
kind: Service
metadata:
  name: {{ include "vote.fullname" . }}
  labels:
    app: { include "vote.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "vote-service"
    port: {{ .Values.service.port }}
    targetPort: 80
    nodePort: 31000
  selector:
    app: { include "vote.name" . }}
  
